### ISSUE TITLE
Assorted issues trying to use this playbook

### ISSUE THREAD

**Issue by kuza55** [jenkstom/ansible-jupyterhub#1]
Some issues I noticed with this playbook that made it hard to use:

The role has a preconfigured password that's not configurable with a variable; At first I added a command to change the password after this role had run, but this is suboptimal.

I tried to use this straight from galaxy and it refused to run without the --no-ssl flag, giving me this error:

[E 2016-06-29 20:47:15.142 JupyterHub app:963] Refusing to run JuptyterHub without SSL. If you are terminating SSL in another layer, pass --no-ssl to tell JupyterHub to allow the proxy to listen on HTTP.

At this point I had to grab the role from github and make changes to the init file.

After making changes to the init file and running the role again, I got this error:

FAILED! => {"changed": false, "cmd": "/usr/bin/easy_install --dry-run pip", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

I'm guessing something in the role is removing this file making this role unable to run twice by default, but if this file is expected to be removed there should be some check to skip this command if so. Commenting out that line from the role let it run.

**Comment by jenkstom** [comment]
I have remove the easy_install line since it isn't necessary. The password is now a prompt.
