### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by patpicos** [jenkstom/ansible-jupyterhub#3]
openssl req -new -nodes -x509 -subj "/C=NoCountry/ST=NoState/L=NoCity/O=IT*

Fails because C= is expected to have a 2 char value such as US 

Moving the values to prompts may be useful so that consumers dont have to edit the role

**Comment by jenkstom** [comment]
Prompts are not supported in roles. I am creating a sample playbook and adding prompts there for this and for the jupyterhub password.

**Comment by jenkstom** [comment]
I've added prompts in the example playbook. It will always ask for prompts. If the key file already exists, the certificate is not recreated. This fixes this issue as well as can be with ansible's limitations.
