### ISSUE TITLE
test directory does not exist

### ISSUE THREAD

**Issue by jottr** [jenkstom/ansible-jupyterhub#5]
In the readme you write  `ansible-playbook ansible-jupyterhub/test/test.yml -i ansible-jupyterhub/test/hosts` should be used to run the playbook.
The `test`-directory does not exist.

**Comment by jenkstom** [comment]
Could you see if instructions work better now?

**Comment by jottr** [comment]
Looks like it. I've since moved on to https://github.com/jupyterhub/jupyterhub-deploy-teaching
Thx.
